--create table address (id bigint generated by default as identity, city varchar(255), country varchar(255), neighborhood varchar(255), number varchar(255), post_code varchar(255), province varchar(255), street varchar(255), customer_id bigint, primary key (id));
--create table customer (id bigint generated by default as identity, document varchar(255), name varchar(255), primary key (id));
--alter table customer add constraint UK_phlle50dp6ivt0paa1d5gkvk2 unique (document);
--alter table address add constraint FK93c3js0e22ll1xlu21nvrhqgg foreign key (customer_id) references customer;

insert into customer (id, document, name) values (null, '10836971531', 'Martin Julio Kaique Novaes')
insert into address (id, city, country, neighborhood, number, post_code, province, street, customer_id) values (null, 'Parnamirim', 'Brasil', 'Emaús', '515', '59149-255', 'RN', 'Rua Rio Tigre', '1')
insert into address (id, city, country, neighborhood, number, post_code, province, street, customer_id) values (null, 'Natal', 'Brasil', 'Ponta Negra', 's/n', '59018-500', 'RN', 'Av. Dep. Antônio Florêncio de Queiroz', '1')
